package org.example.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public java.lang.Integer getOrderId() {
		return getInt("order_id");
	}

	public void setOrderId(java.lang.Integer orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderName() {
		return getStr("order_name");
	}

	public void setOrderName(java.lang.String orderName) {
		set("order_name", orderName);
	}

}

